### ISSUE TITLE
Module / RX version formatting

### ISSUE THREAD

**Issue by CarlKnox** [EdgeTX/buddy#34]
Nightly build for TX16S, 2.8.0-nightly (ba814db3), places the 'e' from Multimodule on a second line while there is plenty of space to slide the version to the right.

**Comment by pfeerick** [comment]
Thanks for the report. FYI, this is the wrong repo to be reporting this on - this is the repo for the buddy firmware flasher, not the main firmware ;)

Ah, I see the problem - and there actually isn't enough space, since it's supposed to be one one line. I'll probably change it to MPM, but I bet the NV14 screen is even worse since it's portrait orientation (i.e. TX16S screen, rotated 90 degrees), so might have change it so the version is shown on a second line.

**Comment by pfeerick** [comment]
@freshollie You can close this issue - it has been resolved (even though it was in the wrong repo) ;)
